#!/usr/bin/env bash
# Is this repository safe to publish? Run it before every push: `make public-check`.
#
#   1. nothing private is tracked — .env, secrets/, runtime state, keys, your own descriptors;
#   2. no secret is anywhere in the working tree or in the history that a push would carry,
#      according to Gitleaks, pinned to one version and run from its own image;
#   3. the scanner is actually working — a control it must reject is fed to it every time, from a
#      temporary directory, so no credential-shaped string is ever committed to prove the point.
#
# It exits non-zero on the first failure and says what to do. Nothing here is a substitute for
# reading `AGENTS.md`: a gate that is bypassed is not a gate.
set -uo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO="$(cd -- "$HERE/.." && pwd -P)"
GITLEAKS_VERSION="v8.29.0"
GITLEAKS_IMAGE="ghcr.io/gitleaks/gitleaks:$GITLEAKS_VERSION"
FAILED=0

say() { printf '%s %s\n' "$1" "$2"; }
fail() { say "FAIL" "$1"; FAILED=1; }
pass() { say "ok  " "$1"; }

cd "$REPO" || exit 2

# ---- 1. what is tracked ---------------------------------------------------------------------

tracked() { git ls-files -- "$@" 2>/dev/null; }

for path in .env secrets repos.json tmp; do
    if [ -n "$(tracked "$path" "$path/**")" ]; then
        fail "$path is tracked; it is private to a machine or generated by a run"
    else
        pass "$path is not tracked"
    fi
done

keys="$(tracked '*.pem' '*.key' '*.p12' '*.pfx' '*.token' | grep -v '^workbench/vendor/' || true)"
if [ -n "$keys" ]; then
    fail "key or token files are tracked: $(echo "$keys" | tr '\n' ' ')"
else
    pass "no key or token files are tracked"
fi

runtime="$(tracked '*.out' '*.err' '*.prompt' '*.events' '*.pid' '*.log' || true)"
if [ -n "$runtime" ]; then
    fail "run artefacts are tracked: $(echo "$runtime" | tr '\n' ' ')"
else
    pass "no run artefacts are tracked"
fi

# Debris of local acceptance: a throwaway repository or probe that must never be committed.
debris="$(tracked '*orch-accept*' '*trustprobe*' '*acceptance-*' || true)"
if [ -n "$debris" ]; then
    fail "acceptance debris is tracked: $(echo "$debris" | tr '\n' ' ')"
else
    pass "no acceptance debris is tracked"
fi

# ---- 2. the scanner, and proof that it is working -------------------------------------------

if ! command -v docker >/dev/null 2>&1; then
    fail "docker is needed to run Gitleaks $GITLEAKS_VERSION; install it or run the scanner yourself"
    exit 1
fi

gitleaks() { docker run --rm -v "$1:/scan:ro" -w /scan "$GITLEAKS_IMAGE" "${@:2}"; }

control="$(mktemp -d)"
trap 'rm -rf "$control"' EXIT
# A credential shape the scanner must recognise, assembled here so the string exists only in a
# temporary directory — never in a commit, and never usable. Neither a documented example key nor an
# obvious placeholder: measured, the scanner allowlists both, and a control it ignores proves nothing.
printf 'token = "ghp_%s"\n' "a1b2c3d4e5a1b2c3d4e5a1b2c3d4e5abcdef" > "$control/control.txt"
if gitleaks "$control" detect --no-git --no-banner --redact >/dev/null 2>&1; then
    fail "the control was not rejected: Gitleaks is not scanning, so its silence means nothing"
else
    pass "the scanner rejects a known-bad control"
fi

if gitleaks "$REPO" detect --no-git --no-banner --redact --exit-code 1 >/tmp/gitleaks-worktree.txt 2>&1; then
    pass "no secret in the working tree"
else
    fail "Gitleaks found something in the working tree:"
    sed 's/^/     /' /tmp/gitleaks-worktree.txt | head -40
fi

if [ -d "$REPO/.git" ]; then
    if gitleaks "$REPO" detect --no-banner --redact --exit-code 1 >/tmp/gitleaks-history.txt 2>&1; then
        pass "no secret in the history a push would carry"
    else
        fail "Gitleaks found something in the history:"
        sed 's/^/     /' /tmp/gitleaks-history.txt | head -40
    fi
fi

# ---- 3. the working tree itself --------------------------------------------------------------

if git diff --check >/dev/null 2>&1; then
    pass "git diff --check is clean"
else
    fail "git diff --check reports whitespace errors"
fi

echo
if [ "$FAILED" -eq 0 ]; then
    echo "PUBLIC CHECK PASSED"
else
    echo "PUBLIC CHECK FAILED - do not push"
fi
exit "$FAILED"
